"""empty message

Revision ID: f1325c0b6b0b
Revises: 1cc051a1ee1a
Create Date: 2018-04-05 14:56:11.720561

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f1325c0b6b0b'
down_revision = '1cc051a1ee1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer',
                  sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('project',
                  sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('end', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('start', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'start')
    op.drop_column('task', 'end')
    op.drop_column('task', 'created_at')
    op.drop_column('project', 'created_at')
    op.drop_column('customer', 'created_at')
    # ### end Alembic commands ###
